server:
  port: 8889

spring:
  zipkin:
    enabled: true
    base-url: ${zipkin_url}
    service:
      name: config-server-git


  application:
    name: config-server-git


  cloud:
    config:
      server:
        git:
          uri: ${config_uri}
          default-label: main
          skip-ssl-validation: true
          username: ${config_username}
          password: ${GIT_JAVA6_KEY}